---
- name: Download Elasticsearch
  get_url: url=https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/rpm/elasticsearch/2.1.1/elasticsearch-2.1.1.rpm dest=/tmp

- name: Install ES rpm package
  yum:
    name: /tmp/elasticsearch-2.1.1.rpm
  sudo: yes

- name: ES config file
  template:
    src=elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root group=root mode=644
  sudo: yes
  notify: Restart elasticsearch


