---
- name: WenUpd8 apt repo
  apt_repository:
    repo='ppa:webupd8team/java'
    update_cache=yes
  sudo: yes

- name: Check Oracle license
  shell:
    /usr/bin/debconf-show oracle-java8-installer |awk '/accepted-oracle-license/{print $NF}'
  sudo: yes
  changed_when: False
  register: webupd8team

- name: Accept Oracle license
  shell:
    echo 'oracle-java8-installer shared/accepted-oracle-license-v1-1 select true' | /usr/bin/debconf-set-selections
  sudo: yes
  when: webupd8team.stdout != 'true'

- name: Oracle Java apt install
  apt: pkg=oracle-java8-installer update_cache=yes state=present
  sudo: yes
